export const SHARE_MODAL_OPENING_REQUESTED = 'theme/SHARE_MODAL_OPENING_REQUESTED';
export const SHARE_MODAL_OPENING_STARTED = 'theme/SHARE_MODAL_OPENING_STARTED';
export const SHARE_MODAL_OPENING_FINISHED = 'theme/SHARE_MODAL_OPENING_FINISHED';
export const SHARE_MODAL_CLOSING_REQUESTED = 'theme/SHARE_MODAL_CLOSING_REQUESTED';
export const SHARE_MODAL_CLOSING_STARTED = 'theme/SHARE_MODAL_CLOSING_STARTED';
export const SHARE_MODAL_CLOSING_FINISHED = 'theme/SHARE_MODAL_CLOSING_FINISHED';

export const ALL_SHARE_COUNT_REQUESTED = 'theme/ALL_SHARE_COUNT_REQUESTED';
export const ALL_SHARE_COUNT_RESOLVED = 'theme/ALL_SHARE_COUNT_RESOLVED';

export const SHARE_COUNT_REQUESTED = 'theme/SHARE_COUNT_REQUESTED';
export const SHARE_COUNT_SUCCEED = 'theme/SHARE_COUNT_SUCCEED';
export const SHARE_COUNT_FAILED = 'theme/SHARE_COUNT_FAILED';

export const LINK_COPIED = 'theme/LINK_COPIED';

export const TOGGLE_COMMENTS = 'theme/TOGGLE_COMMENTS';

export const ACTIVE_POST_SLIDE_CHANGE_REQUESTED = 'theme/ACTIVE_POST_SLIDE_CHANGE_REQUESTED';
export const ACTIVE_POST_SLIDE_CHANGE_STARTED = 'theme/ACTIVE_POST_SLIDE_CHANGE_STARTED';
export const ACTIVE_POST_SLIDE_CHANGE_FINISHED = 'theme/ACTIVE_POST_SLIDE_CHANGE_FINISHED';

export const POST_HAS_SCROLLED = 'theme/POST_HAS_SCROLLED';

export const BARS_HAVE_HIDDEN = 'theme/BARS_HAVE_HIDDEN';
export const BARS_HAVE_SHOWN = 'theme/BARS_HAVE_SHOWN';

export const MENU_HAS_OPEN = 'theme/MENU_HAS_OPEN';
export const MENU_HAS_CLOSED = 'theme/MENU_HAS_CLOSED';

export const COOKIES_HAVE_BEEN_REQUESTED = 'theme/COOKIES_HAVE_BEEN_REQUESTED';
export const COOKIES_HAVE_BEEN_ACCEPTED = 'theme/COOKIES_HAVE_BEEN_ACCEPTED';

export const NAV_DID_MOUNT = 'theme/NAV_DID_MOUNT';

export const CLASSIC_VERSION_REQUESTED = 'theme/CLASSIC_VERSION_REQUESTED';

export const NOTIFICATIONS_HAS_BEEN_ENABLED = 'theme/NOTIFICATIONS_HAS_BEEN_ENABLED';
export const NOTIFICATIONS_HAS_BEEN_DISABLED = 'theme/NOTIFICATIONS_HAS_BEEN_DISABLED';
