export const SHARE_MODAL_OPENING_REQUESTED = 'theme/SHARE_MODAL_OPENING_REQUESTED';
export const SHARE_MODAL_OPENING_STARTED = 'theme/SHARE_MODAL_OPENING_STARTED';
export const SHARE_MODAL_OPENING_FINISHED = 'theme/SHARE_MODAL_OPENING_FINISHED';
export const SHARE_MODAL_CLOSING_REQUESTED = 'theme/SHARE_MODAL_CLOSING_REQUESTED';
export const SHARE_MODAL_CLOSING_STARTED = 'theme/SHARE_MODAL_CLOSING_STARTED';
export const SHARE_MODAL_CLOSING_FINISHED = 'theme/SHARE_MODAL_CLOSING_FINISHED';

export const ALL_SHARE_COUNT_REQUESTED = 'theme/ALL_SHARE_COUNT_REQUESTED';
export const ALL_SHARE_COUNT_RESOLVED = 'theme/ALL_SHARE_COUNT_RESOLVED';

export const SHARE_COUNT_REQUESTED = 'theme/SHARE_COUNT_REQUESTED';
export const SHARE_COUNT_SUCCEED = 'theme/SHARE_COUNT_SUCCEED';
export const SHARE_COUNT_FAILED = 'theme/SHARE_COUNT_FAILED';

export const LINK_COPIED = 'theme/LINK_COPIED';
export const LINK_SHARED = 'theme/LINK_SHARED';

export const COMMENTS_HAVE_OPEN = 'theme/COMMENTS_HAVE_OPEN';
export const COMMENTS_HAVE_CLOSED = 'theme/COMMENTS_HAVE_CLOSED';

export const ACTIVE_POST_SLIDE_CHANGE_REQUESTED = 'theme/ACTIVE_POST_SLIDE_CHANGE_REQUESTED';
export const ACTIVE_POST_SLIDE_CHANGE_STARTED = 'theme/ACTIVE_POST_SLIDE_CHANGE_STARTED';
export const ACTIVE_POST_SLIDE_CHANGE_FINISHED = 'theme/ACTIVE_POST_SLIDE_CHANGE_FINISHED';

export const WINDOW_HAS_SCROLLED = 'theme/WINDOW_HAS_SCROLLED';

export const BARS_HAVE_HIDDEN = 'theme/BARS_HAVE_HIDDEN';
export const BARS_HAVE_SHOWN = 'theme/BARS_HAVE_SHOWN';

export const NAV_DID_MOUNT = 'theme/NAV_DID_MOUNT';

export const CLASSIC_VERSION_REQUESTED = 'theme/CLASSIC_VERSION_REQUESTED';

export const NOTIFICATIONS_HAVE_BEEN_REQUESTED = 'theme/NOTIFICATIONS_HAVE_BEEN_REQUESTED';
export const NOTIFICATIONS_HAVE_BEEN_ENABLED = 'theme/NOTIFICATIONS_HAVE_BEEN_ENABLED';
export const NOTIFICATIONS_HAVE_BEEN_DISABLED = 'theme/NOTIFICATIONS_HAVE_BEEN_DISABLED';
export const NOTIFICATIONS_ARE_SUPPORTED = 'theme/NOTIFICATIONS_ARE_SUPPORTED';

export const ACTIVE_LIST_SLIDE_HAS_CHANGED = 'theme/ACTIVE_LIST_SLIDE_HAS_CHANGED';
export const ACTIVE_POST_SLIDE_HAS_CHANGED = 'theme/ACTIVE_POST_SLIDE_HAS_CHANGED';

export const STICKY_HAS_SHOWN = 'theme/STICKY_HAS_SHOWN';
export const STICKY_HAS_HIDDEN = 'theme/STICKY_HAS_HIDDEN';
export const STICKY_UPDATE_TIMEOUT = 'theme/STICKY_UPDATE_TIMEOUT';

export const GET_NEXT_PAGE = 'theme/GET_NEXT_PAGE';
